# Generated by Django 3.1.7 on 2021-03-22 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_productie', models.CharField(max_length=2)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wave.date_placi')),
            ],
        ),
    ]
