# Generated by Django 3.1.7 on 2021-05-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0002_productie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productie',
            old_name='line_productie',
            new_name='linie_productie',
        ),
    ]
