# Generated by Django 3.1.7 on 2021-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0005_auto_20210507_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productie',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
