# Generated by Django 3.1.7 on 2021-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0006_auto_20210507_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_placi',
            name='multiplication_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
