# Generated by Django 3.1.7 on 2021-06-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0007_date_placi_multiplication_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_placi',
            name='min_placa',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='date_placi',
            name='multiplication_factor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
