# Generated by Django 3.1.7 on 2021-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0008_auto_20210601_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productie',
            name='multi_factor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
