# Generated by Django 3.1.7 on 2021-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0009_productie_multi_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_placi',
            name='multiplication_factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productie',
            name='multi_factor',
            field=models.IntegerField(default=1),
        ),
    ]
