# Generated by Django 3.1.7 on 2021-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave', '0010_auto_20210609_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_placi',
            name='min_placa',
            field=models.FloatField(),
        ),
    ]
