# Generated by Django 3.1.7 on 2021-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setari_Sonerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('versiune', models.CharField(max_length=200)),
                ('ore', models.CharField(max_length=200)),
            ],
        ),
    ]
