# Generated by Django 3.1.7 on 2021-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonerie', '0003_sonerii_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Sonerii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('versiune', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ore_Sonerii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.TimeField()),
                ('status', models.BooleanField()),
                ('soneria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonerie.info_sonerii')),
            ],
        ),
        migrations.DeleteModel(
            name='Sonerii',
        ),
    ]
