# Generated by Django 3.1.7 on 2021-07-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Placi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_placa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Defecte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('barcode', models.CharField(max_length=200)),
                ('step_fail', models.CharField(max_length=200)),
                ('defect', models.CharField(max_length=1000)),
                ('problem', models.CharField(max_length=1000)),
                ('component_phase_reference', models.CharField(max_length=200)),
                ('action_performed', models.CharField(max_length=200)),
                ('functional_test', models.BooleanField()),
                ('security_test', models.BooleanField()),
                ('tip_componenta', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=200)),
                ('commessa', models.CharField(max_length=200)),
                ('produs_in', models.CharField(max_length=200)),
                ('cod_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defecte.date_placi')),
            ],
        ),
    ]
