# Generated by Django 3.1.7 on 2021-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defecte', '0004_auto_20210813_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='my_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
